### ISSUE TITLE
[Idea] Integration of Ruffle

### ISSUE THREAD

**Issue by SeleDreams** [KuromeSan/TamaTown#2]
As flash player is going to die including all the adobe tools for it, i'm thinking maybe ruffle should be integrated to the website, it's an open source replacement to flash that can be directly integrated in a webpage to make it play flash content without the need of the user to install anything
https://ruffle.rs/

**Comment by SeleDreams** [comment]
I just tested with the standalone ruffle and it is working so i do think the swf could be bundled in an html page with the ruffle player as well and it would work

**Comment by KuromeSan** [comment]
i already tried using ruffle and it didnt work properly- see http://famita.ml/pc/flashless.html
and ulthough the main world loads fine- certain minigames do not-

oh and friends? is AS3 which ruffle has 0 support for atm

**Comment by SeleDreams** [comment]
> i already tried using ruffle and it didnt work properly- see http://famita.ml/pc/flashless.html
> and ulthough the main world loads fine- certain minigames do not- (like the travel agency for example)
> 
> oh and friends is AS3 which ruffle has 0 support for atm... kinda sucks-

could a flash swf be reversed ? in this case maybe porting it to haxe might be interesting, haxe is meant to be easily portable from old actionscript code

**Comment by SeleDreams** [comment]
https://github.com/andreasdr/xfl I'll be looking into this to see if the process is doable, i noticed i could reverse the swf to xfl

**Comment by KuromeSan** [comment]
theres decompilers that give you the .fla file used to build the swf too ..
